version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    image: php:7.4-fpm
    container_name: php-container
    volumes:
      - ./html:/var/www/html
    networks:
      - mynetwork

  # Optional: Redis (if required for caching or sessions)
  redis:
    image: redis:alpine
    container_name: redis-container
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
